stages:
- name: creat
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: harbor.yfw.com:180/lhc/demo:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: harbor.yfw.com:180
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
