stages:
- name: creat
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: lhc/demo:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: 192.168.2.247:180
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
