stages:
- name: build
  steps:
  - runScriptConfig:
      image: nginx:1.18.0
      shellScript: |
        #!/bin/bash
        touch Dockerfile

        cat > Dockerfile << 'EOF'
        From nginx:1.18.0
        ENV WWW /usr/share/nginx/html
        RUN echo 'Asia/Shanghai' >/etc/timezone
        WORKDIR $WWW
        ADD index.html $WWW/index.html
        CMD ["nginx","-g","daemon off;"]
        EOF
- name: creat
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: harbor.yfw.com:180/lhc/nginx:v1
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
