stages:
- name: creat
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: 127.0.0.1:34630/demo:${CICD_EXECUTION_SEQUENCE}
      registry: 127.0.0.1:34630
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
